### ISSUE TITLE
Optional censoring of NSFW posts

### ISSUE THREAD

**Issue by buresdv** [mormaer/Mlem#61]
## Introduction
That one guy in the Mlem community doesn't want to see furry porn. This has to be implemented and turned on by default to comply with Apple's guidelines (guideline 1.2).

## Discussion
Related to #62. When the blurred picture is tapped, it should unblur and expand only when tapped.

## Requirements
Add the bluring of NSFW posts. This should be optional and have a setting.

**Comment by ShadowJonathan** [comment]
This is also necessary to pass apple review, so this'll definitely get added before v1

**Comment by Kulkinz** [comment]
Yeah can second wanting this feature. Was scrolling my feed on the bus, got a post that was tagged NSFW but app didnt blur so just showed right around, so would rather avoid that ahah.

**Comment by jenkshields** [comment]
I’ve just found a good workaround for now - Mlem respects your “view nsfw content” setting on your instance - so I’ve set that to hide on web and it’s reflected in the app.

**Comment by EricBAndrews** [comment]
I've got a followup to the Post Overhaul PR in the works to catch all the stuff I couldn't put in that one--I'll add this to that

**Comment by EricBAndrews** [comment]
Closed in #204

**Comment by BaelfireNightshd** [comment]
I don't think this is resolved yet. 

In the latest version that was available on TestFlight, only the very first image is blurred. I'm working on getting another account to be able to take a screenshot (since NSFW content is not visible unless you have an account. And it seems that Lemmy will gladly not blur your own content. Which doesn't make sense.) In the meantime, here's a link to the test post I made. https://beehaw.org/post/710425 (also not sure how to get a lemmy.ml link for that post...)

**Comment by EricBAndrews** [comment]
Reopened per comment above.

**Comment by BrooklynMan** [comment]
> And it seems that Lemmy will gladly not blur your own content. Which doesn't make sense.) 

I suppose this may be because the reasoning was that it doesn't need to hide something you've already seen (since it's 8Your* content), but it's still a dumb decision. we'll look into this.

**Comment by ShadowJonathan** [comment]
This should have been a new issue, closing to shift focus of the new issue to a new ticket; #291
