### ISSUE TITLE
Give users a way to view their subscribed communities in a list

### ISSUE THREAD

**Issue by fireshaper** [mormaer/Mlem#78]
## Introduction
Users should be able to view all their subscribed communities in one place. 

## Requirements
Add a list of subscribed communities to the app, maybe in the top drop down. 

## Discussion
To make it easier to navigate, users shouldn’t have to rely on the main “subscribed” feed if they want to see specific content. 

## What I Need
Show a list of subscribed communities.

**Comment by peruginiandrea** [comment]
Rather than adding all the subscribed communities in the top drop-down menus, I would suggest using a similar approach to Apollo (Reddit app). In this case, the drop down menu would stay as it is now, but there would be a dedicated page (not sure what the correct terminology is, sorry) on the left, that you can access with a swipe, where you can scroll through all subscribed communities.

This way the top bar would not be cluttered and would world well for quick access to favorites and search, while everything else would be on a dedicated area.

**Comment by porkins** [comment]
![IMG_2395](https://github.com/buresdv/Mlem/assets/136361564/854154ba-e4a6-4064-b8ff-43f4f1ba9cdb)
![IMG_2396](https://github.com/buresdv/Mlem/assets/136361564/7dc40419-a6bd-45a9-a8bb-bd70e5bc15c8)

Adding examples for reference.

**Comment by robzombie91** [comment]
+1, would love to see this implemented

**Comment by JakeShirley** [comment]
Here is the version that's in #197 now, hopefully in the next release!

![image](https://github.com/buresdv/Mlem/assets/1000311/c3c9591c-2141-46cb-b0f4-c7a541d4b04e)

**Comment by ShadowJonathan** [comment]
This is in 0.1.0 (14) now

There is a bug with this at https://github.com/mormaer/Mlem/issues/242, but this feature is closed and done.
